
import * as d from './proxies';

export const DIRECTIVES = [
  d.SignalAppShell,
  d.SignalBadge,
  d.SignalButton,
  d.SignalCard,
  d.SignalCheckbox,
  d.SignalCombobox,
  d.SignalDataTable,
  d.SignalFeatureTable,
  d.SignalFileUpload,
  d.SignalHeading,
  d.SignalInput,
  d.SignalLayout,
  d.SignalListItem,
  d.SignalModal,
  d.SignalPage,
  d.SignalProgress,
  d.SignalRadioGroup,
  d.SignalSection,
  d.SignalSelect,
  d.SignalSidebar,
  d.SignalSkeleton,
  d.SignalSlider,
  d.SignalSnackbar,
  d.SignalSplitView,
  d.SignalSwitch,
  d.SignalTable,
  d.SignalTag,
  d.SignalText,
  d.SignalTextarea,
  d.SignalToast,
  d.SignalTooltip
];
