'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalSelectCustomEvent } from "@signal-web-ui/core";
import { SignalSelect as SignalSelectElement, defineCustomElement as defineSignalSelect } from "@signal-web-ui/core/dist/custom-elements/signal-select.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalSelectEvents = { onValueChange: EventName<SignalSelectCustomEvent<{ value: string | undefined }>> };

export const SignalSelect: StencilReactComponent<SignalSelectElement, SignalSelectEvents> = /*@__PURE__*/ createComponent<SignalSelectElement, SignalSelectEvents>({
    tagName: 'signal-select',
    elementClass: SignalSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as SignalSelectEvents,
    defineCustomElement: defineSignalSelect
});
