'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalBadge as SignalBadgeElement, defineCustomElement as defineSignalBadge } from "@signal-web-ui/core/dist/custom-elements/signal-badge.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalBadgeEvents = NonNullable<unknown>;

export const SignalBadge: StencilReactComponent<SignalBadgeElement, SignalBadgeEvents> = /*@__PURE__*/ createComponent<SignalBadgeElement, SignalBadgeEvents>({
    tagName: 'signal-badge',
    elementClass: SignalBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalBadgeEvents,
    defineCustomElement: defineSignalBadge
});
