'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalSection as SignalSectionElement, defineCustomElement as defineSignalSection } from "@signal-web-ui/core/dist/custom-elements/signal-section.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalSectionEvents = NonNullable<unknown>;

export const SignalSection: StencilReactComponent<SignalSectionElement, SignalSectionEvents> = /*@__PURE__*/ createComponent<SignalSectionElement, SignalSectionEvents>({
    tagName: 'signal-section',
    elementClass: SignalSectionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalSectionEvents,
    defineCustomElement: defineSignalSection
});
