'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalInputCustomEvent } from "@signal-web-ui/core";
import { SignalInput as SignalInputElement, defineCustomElement as defineSignalInput } from "@signal-web-ui/core/dist/custom-elements/signal-input.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalInputEvents = {
    onValueInput: EventName<SignalInputCustomEvent<{ value: string }>>,
    onValueChange: EventName<SignalInputCustomEvent<{ value: string }>>
};

export const SignalInput: StencilReactComponent<SignalInputElement, SignalInputEvents> = /*@__PURE__*/ createComponent<SignalInputElement, SignalInputEvents>({
    tagName: 'signal-input',
    elementClass: SignalInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueInput: 'valueInput',
        onValueChange: 'valueChange'
    } as SignalInputEvents,
    defineCustomElement: defineSignalInput
});
