'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalSidebarCustomEvent } from "@signal-web-ui/core";
import { SignalSidebar as SignalSidebarElement, defineCustomElement as defineSignalSidebar } from "@signal-web-ui/core/dist/custom-elements/signal-sidebar.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalSidebarEvents = {
    onNavigate: EventName<SignalSidebarCustomEvent<{ id: string }>>,
    onToggle: EventName<SignalSidebarCustomEvent<{ collapsed: boolean }>>
};

export const SignalSidebar: StencilReactComponent<SignalSidebarElement, SignalSidebarEvents> = /*@__PURE__*/ createComponent<SignalSidebarElement, SignalSidebarEvents>({
    tagName: 'signal-sidebar',
    elementClass: SignalSidebarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onNavigate: 'navigate',
        onToggle: 'toggle'
    } as SignalSidebarEvents,
    defineCustomElement: defineSignalSidebar
});
