'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalTagCustomEvent } from "@signal-web-ui/core";
import { SignalTag as SignalTagElement, defineCustomElement as defineSignalTag } from "@signal-web-ui/core/dist/custom-elements/signal-tag.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalTagEvents = { onRemove: EventName<SignalTagCustomEvent<void>> };

export const SignalTag: StencilReactComponent<SignalTagElement, SignalTagEvents> = /*@__PURE__*/ createComponent<SignalTagElement, SignalTagEvents>({
    tagName: 'signal-tag',
    elementClass: SignalTagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onRemove: 'remove' } as SignalTagEvents,
    defineCustomElement: defineSignalTag
});
