'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalRadioGroupCustomEvent } from "@signal-web-ui/core";
import { SignalRadioGroup as SignalRadioGroupElement, defineCustomElement as defineSignalRadioGroup } from "@signal-web-ui/core/dist/custom-elements/signal-radio-group.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalRadioGroupEvents = { onValueChange: EventName<SignalRadioGroupCustomEvent<{ value: string | undefined }>> };

export const SignalRadioGroup: StencilReactComponent<SignalRadioGroupElement, SignalRadioGroupEvents> = /*@__PURE__*/ createComponent<SignalRadioGroupElement, SignalRadioGroupEvents>({
    tagName: 'signal-radio-group',
    elementClass: SignalRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as SignalRadioGroupEvents,
    defineCustomElement: defineSignalRadioGroup
});
