'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalSnackbarCustomEvent } from "@signal-web-ui/core";
import { SignalSnackbar as SignalSnackbarElement, defineCustomElement as defineSignalSnackbar } from "@signal-web-ui/core/dist/custom-elements/signal-snackbar.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalSnackbarEvents = {
    onAction: EventName<SignalSnackbarCustomEvent<void>>,
    onDismiss: EventName<SignalSnackbarCustomEvent<void>>
};

export const SignalSnackbar: StencilReactComponent<SignalSnackbarElement, SignalSnackbarEvents> = /*@__PURE__*/ createComponent<SignalSnackbarElement, SignalSnackbarEvents>({
    tagName: 'signal-snackbar',
    elementClass: SignalSnackbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onAction: 'action',
        onDismiss: 'dismiss'
    } as SignalSnackbarEvents,
    defineCustomElement: defineSignalSnackbar
});
