'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalTableCustomEvent } from "@signal-web-ui/core";
import { SignalTable as SignalTableElement, defineCustomElement as defineSignalTable } from "@signal-web-ui/core/dist/custom-elements/signal-table.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalTableEvents = {
    onRowClick: EventName<SignalTableCustomEvent<{ row: Record<string, unknown> }>>,
    onReorder: EventName<SignalTableCustomEvent<{ rows: Record<string, unknown>[] }>>,
    onSearchChange: EventName<SignalTableCustomEvent<{ query: string }>>,
    onFilterChange: EventName<SignalTableCustomEvent<{ filters: Record<string, string> }>>
};

export const SignalTable: StencilReactComponent<SignalTableElement, SignalTableEvents> = /*@__PURE__*/ createComponent<SignalTableElement, SignalTableEvents>({
    tagName: 'signal-table',
    elementClass: SignalTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onRowClick: 'rowClick',
        onReorder: 'reorder',
        onSearchChange: 'searchChange',
        onFilterChange: 'filterChange'
    } as SignalTableEvents,
    defineCustomElement: defineSignalTable
});
