'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalSwitchCustomEvent } from "@signal-web-ui/core";
import { SignalSwitch as SignalSwitchElement, defineCustomElement as defineSignalSwitch } from "@signal-web-ui/core/dist/custom-elements/signal-switch.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalSwitchEvents = { onValueChange: EventName<SignalSwitchCustomEvent<{ checked: boolean }>> };

export const SignalSwitch: StencilReactComponent<SignalSwitchElement, SignalSwitchEvents> = /*@__PURE__*/ createComponent<SignalSwitchElement, SignalSwitchEvents>({
    tagName: 'signal-switch',
    elementClass: SignalSwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as SignalSwitchEvents,
    defineCustomElement: defineSignalSwitch
});
