'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalBehavioralPrimitives as SignalBehavioralPrimitivesElement, defineCustomElement as defineSignalBehavioralPrimitives } from "@signal-web-ui/core/dist/custom-elements/signal-behavioral-primitives.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalBehavioralPrimitivesEvents = NonNullable<unknown>;

export const SignalBehavioralPrimitives: StencilReactComponent<SignalBehavioralPrimitivesElement, SignalBehavioralPrimitivesEvents> = /*@__PURE__*/ createComponent<SignalBehavioralPrimitivesElement, SignalBehavioralPrimitivesEvents>({
    tagName: 'signal-behavioral-primitives',
    elementClass: SignalBehavioralPrimitivesElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalBehavioralPrimitivesEvents,
    defineCustomElement: defineSignalBehavioralPrimitives
});
