'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalCheckboxCustomEvent } from "@signal-web-ui/core";
import { SignalCheckbox as SignalCheckboxElement, defineCustomElement as defineSignalCheckbox } from "@signal-web-ui/core/dist/custom-elements/signal-checkbox.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalCheckboxEvents = { onValueChange: EventName<SignalCheckboxCustomEvent<{ checked: boolean }>> };

export const SignalCheckbox: StencilReactComponent<SignalCheckboxElement, SignalCheckboxEvents> = /*@__PURE__*/ createComponent<SignalCheckboxElement, SignalCheckboxEvents>({
    tagName: 'signal-checkbox',
    elementClass: SignalCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as SignalCheckboxEvents,
    defineCustomElement: defineSignalCheckbox
});
