'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalSliderCustomEvent } from "@signal-web-ui/core";
import { SignalSlider as SignalSliderElement, defineCustomElement as defineSignalSlider } from "@signal-web-ui/core/dist/custom-elements/signal-slider.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalSliderEvents = { onValueChange: EventName<SignalSliderCustomEvent<{ value: number | [number, number] }>> };

export const SignalSlider: StencilReactComponent<SignalSliderElement, SignalSliderEvents> = /*@__PURE__*/ createComponent<SignalSliderElement, SignalSliderEvents>({
    tagName: 'signal-slider',
    elementClass: SignalSliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as SignalSliderEvents,
    defineCustomElement: defineSignalSlider
});
