'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalNavbarCustomEvent } from "@signal-web-ui/core";
import { SignalNavbar as SignalNavbarElement, defineCustomElement as defineSignalNavbar } from "@signal-web-ui/core/dist/custom-elements/signal-navbar.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalNavbarEvents = { onNavigate: EventName<SignalNavbarCustomEvent<{ id: string }>> };

export const SignalNavbar: StencilReactComponent<SignalNavbarElement, SignalNavbarEvents> = /*@__PURE__*/ createComponent<SignalNavbarElement, SignalNavbarEvents>({
    tagName: 'signal-navbar',
    elementClass: SignalNavbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onNavigate: 'navigate' } as SignalNavbarEvents,
    defineCustomElement: defineSignalNavbar
});
