'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalToastCustomEvent } from "@signal-web-ui/core";
import { SignalToast as SignalToastElement, defineCustomElement as defineSignalToast } from "@signal-web-ui/core/dist/custom-elements/signal-toast.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalToastEvents = {
    onAction: EventName<SignalToastCustomEvent<void>>,
    onDismiss: EventName<SignalToastCustomEvent<void>>
};

export const SignalToast: StencilReactComponent<SignalToastElement, SignalToastEvents> = /*@__PURE__*/ createComponent<SignalToastElement, SignalToastEvents>({
    tagName: 'signal-toast',
    elementClass: SignalToastElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onAction: 'action',
        onDismiss: 'dismiss'
    } as SignalToastEvents,
    defineCustomElement: defineSignalToast
});
