'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalPage as SignalPageElement, defineCustomElement as defineSignalPage } from "@signal-web-ui/core/dist/custom-elements/signal-page.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalPageEvents = NonNullable<unknown>;

export const SignalPage: StencilReactComponent<SignalPageElement, SignalPageEvents> = /*@__PURE__*/ createComponent<SignalPageElement, SignalPageEvents>({
    tagName: 'signal-page',
    elementClass: SignalPageElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalPageEvents,
    defineCustomElement: defineSignalPage
});
