'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalTextareaCustomEvent } from "@signal-web-ui/core";
import { SignalTextarea as SignalTextareaElement, defineCustomElement as defineSignalTextarea } from "@signal-web-ui/core/dist/custom-elements/signal-textarea.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalTextareaEvents = { onValueChange: EventName<SignalTextareaCustomEvent<{ value: string }>> };

export const SignalTextarea: StencilReactComponent<SignalTextareaElement, SignalTextareaEvents> = /*@__PURE__*/ createComponent<SignalTextareaElement, SignalTextareaEvents>({
    tagName: 'signal-textarea',
    elementClass: SignalTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as SignalTextareaEvents,
    defineCustomElement: defineSignalTextarea
});
