'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalCard as SignalCardElement, defineCustomElement as defineSignalCard } from "@signal-web-ui/core/dist/custom-elements/signal-card.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalCardEvents = NonNullable<unknown>;

export const SignalCard: StencilReactComponent<SignalCardElement, SignalCardEvents> = /*@__PURE__*/ createComponent<SignalCardElement, SignalCardEvents>({
    tagName: 'signal-card',
    elementClass: SignalCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalCardEvents,
    defineCustomElement: defineSignalCard
});
