'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalPopoverCustomEvent } from "@signal-web-ui/core";
import { SignalPopover as SignalPopoverElement, defineCustomElement as defineSignalPopover } from "@signal-web-ui/core/dist/custom-elements/signal-popover.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalPopoverEvents = {
    onOpenChange: EventName<SignalPopoverCustomEvent<{ open: boolean }>>,
    onClose: EventName<SignalPopoverCustomEvent<void>>
};

export const SignalPopover: StencilReactComponent<SignalPopoverElement, SignalPopoverEvents> = /*@__PURE__*/ createComponent<SignalPopoverElement, SignalPopoverEvents>({
    tagName: 'signal-popover',
    elementClass: SignalPopoverElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpenChange: 'openChange',
        onClose: 'close'
    } as SignalPopoverEvents,
    defineCustomElement: defineSignalPopover
});
