'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalComboboxCustomEvent } from "@signal-web-ui/core";
import { SignalCombobox as SignalComboboxElement, defineCustomElement as defineSignalCombobox } from "@signal-web-ui/core/dist/custom-elements/signal-combobox.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalComboboxEvents = {
    onValueChange: EventName<SignalComboboxCustomEvent<{ value: string | string[] | null }>>,
    onOpenChange: EventName<SignalComboboxCustomEvent<{ open: boolean }>>,
    onQueryChange: EventName<SignalComboboxCustomEvent<{ query: string }>>,
    onClear: EventName<SignalComboboxCustomEvent<void>>
};

export const SignalCombobox: StencilReactComponent<SignalComboboxElement, SignalComboboxEvents> = /*@__PURE__*/ createComponent<SignalComboboxElement, SignalComboboxEvents>({
    tagName: 'signal-combobox',
    elementClass: SignalComboboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onOpenChange: 'openChange',
        onQueryChange: 'queryChange',
        onClear: 'clear'
    } as SignalComboboxEvents,
    defineCustomElement: defineSignalCombobox
});
