'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalButton as SignalButtonElement, defineCustomElement as defineSignalButton } from "@signal-web-ui/core/dist/custom-elements/signal-button.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalButtonEvents = NonNullable<unknown>;

export const SignalButton: StencilReactComponent<SignalButtonElement, SignalButtonEvents> = /*@__PURE__*/ createComponent<SignalButtonElement, SignalButtonEvents>({
    tagName: 'signal-button',
    elementClass: SignalButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalButtonEvents,
    defineCustomElement: defineSignalButton
});
