'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalAppShell as SignalAppShellElement, defineCustomElement as defineSignalAppShell } from "@signal-web-ui/core/dist/custom-elements/signal-app-shell.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalAppShellEvents = NonNullable<unknown>;

export const SignalAppShell: StencilReactComponent<SignalAppShellElement, SignalAppShellEvents> = /*@__PURE__*/ createComponent<SignalAppShellElement, SignalAppShellEvents>({
    tagName: 'signal-app-shell',
    elementClass: SignalAppShellElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalAppShellEvents,
    defineCustomElement: defineSignalAppShell
});
