'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalBreadcrumbsCustomEvent } from "@signal-web-ui/core";
import { SignalBreadcrumbs as SignalBreadcrumbsElement, defineCustomElement as defineSignalBreadcrumbs } from "@signal-web-ui/core/dist/custom-elements/signal-breadcrumbs.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalBreadcrumbsEvents = { onNavigate: EventName<SignalBreadcrumbsCustomEvent<{ id: string }>> };

export const SignalBreadcrumbs: StencilReactComponent<SignalBreadcrumbsElement, SignalBreadcrumbsEvents> = /*@__PURE__*/ createComponent<SignalBreadcrumbsElement, SignalBreadcrumbsEvents>({
    tagName: 'signal-breadcrumbs',
    elementClass: SignalBreadcrumbsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onNavigate: 'navigate' } as SignalBreadcrumbsEvents,
    defineCustomElement: defineSignalBreadcrumbs
});
