'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalModalCustomEvent } from "@signal-web-ui/core";
import { SignalModal as SignalModalElement, defineCustomElement as defineSignalModal } from "@signal-web-ui/core/dist/custom-elements/signal-modal.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalModalEvents = {
    onOpenChange: EventName<SignalModalCustomEvent<{ open: boolean }>>,
    onClose: EventName<SignalModalCustomEvent<void>>,
    onConfirm: EventName<SignalModalCustomEvent<void>>
};

export const SignalModal: StencilReactComponent<SignalModalElement, SignalModalEvents> = /*@__PURE__*/ createComponent<SignalModalElement, SignalModalEvents>({
    tagName: 'signal-modal',
    elementClass: SignalModalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpenChange: 'openChange',
        onClose: 'close',
        onConfirm: 'confirm'
    } as SignalModalEvents,
    defineCustomElement: defineSignalModal
});
