'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalDropdownCustomEvent } from "@signal-web-ui/core";
import { SignalDropdown as SignalDropdownElement, defineCustomElement as defineSignalDropdown } from "@signal-web-ui/core/dist/custom-elements/signal-dropdown.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalDropdownEvents = {
    onOpenChange: EventName<SignalDropdownCustomEvent<{ open: boolean }>>,
    onItemSelect: EventName<SignalDropdownCustomEvent<{ key: string }>>
};

export const SignalDropdown: StencilReactComponent<SignalDropdownElement, SignalDropdownEvents> = /*@__PURE__*/ createComponent<SignalDropdownElement, SignalDropdownEvents>({
    tagName: 'signal-dropdown',
    elementClass: SignalDropdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpenChange: 'openChange',
        onItemSelect: 'itemSelect'
    } as SignalDropdownEvents,
    defineCustomElement: defineSignalDropdown
});
