'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalProgress as SignalProgressElement, defineCustomElement as defineSignalProgress } from "@signal-web-ui/core/dist/custom-elements/signal-progress.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalProgressEvents = NonNullable<unknown>;

export const SignalProgress: StencilReactComponent<SignalProgressElement, SignalProgressEvents> = /*@__PURE__*/ createComponent<SignalProgressElement, SignalProgressEvents>({
    tagName: 'signal-progress',
    elementClass: SignalProgressElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalProgressEvents,
    defineCustomElement: defineSignalProgress
});
