'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalDrawerCustomEvent } from "@signal-web-ui/core";
import { SignalDrawer as SignalDrawerElement, defineCustomElement as defineSignalDrawer } from "@signal-web-ui/core/dist/custom-elements/signal-drawer.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalDrawerEvents = {
    onOpenChange: EventName<SignalDrawerCustomEvent<{ open: boolean }>>,
    onClose: EventName<SignalDrawerCustomEvent<void>>
};

export const SignalDrawer: StencilReactComponent<SignalDrawerElement, SignalDrawerEvents> = /*@__PURE__*/ createComponent<SignalDrawerElement, SignalDrawerEvents>({
    tagName: 'signal-drawer',
    elementClass: SignalDrawerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onOpenChange: 'openChange',
        onClose: 'close'
    } as SignalDrawerEvents,
    defineCustomElement: defineSignalDrawer
});
