'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalAccessibilityHelpersCustomEvent } from "@signal-web-ui/core";
import { SignalAccessibilityHelpers as SignalAccessibilityHelpersElement, defineCustomElement as defineSignalAccessibilityHelpers } from "@signal-web-ui/core/dist/custom-elements/signal-accessibility-helpers.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalAccessibilityHelpersEvents = { onShortcut: EventName<SignalAccessibilityHelpersCustomEvent<{ combo: string }>> };

export const SignalAccessibilityHelpers: StencilReactComponent<SignalAccessibilityHelpersElement, SignalAccessibilityHelpersEvents> = /*@__PURE__*/ createComponent<SignalAccessibilityHelpersElement, SignalAccessibilityHelpersEvents>({
    tagName: 'signal-accessibility-helpers',
    elementClass: SignalAccessibilityHelpersElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onShortcut: 'shortcut' } as SignalAccessibilityHelpersEvents,
    defineCustomElement: defineSignalAccessibilityHelpers
});
