'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalResponsiveConfig as SignalResponsiveConfigElement, defineCustomElement as defineSignalResponsiveConfig } from "@signal-web-ui/core/dist/custom-elements/signal-responsive-config.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalResponsiveConfigEvents = NonNullable<unknown>;

export const SignalResponsiveConfig: StencilReactComponent<SignalResponsiveConfigElement, SignalResponsiveConfigEvents> = /*@__PURE__*/ createComponent<SignalResponsiveConfigElement, SignalResponsiveConfigEvents>({
    tagName: 'signal-responsive-config',
    elementClass: SignalResponsiveConfigElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalResponsiveConfigEvents,
    defineCustomElement: defineSignalResponsiveConfig
});
