'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalSplitViewCustomEvent } from "@signal-web-ui/core";
import { SignalSplitView as SignalSplitViewElement, defineCustomElement as defineSignalSplitView } from "@signal-web-ui/core/dist/custom-elements/signal-split-view.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalSplitViewEvents = { onSizesChange: EventName<SignalSplitViewCustomEvent<{ sizes: number[] }>> };

export const SignalSplitView: StencilReactComponent<SignalSplitViewElement, SignalSplitViewEvents> = /*@__PURE__*/ createComponent<SignalSplitViewElement, SignalSplitViewEvents>({
    tagName: 'signal-split-view',
    elementClass: SignalSplitViewElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSizesChange: 'sizesChange' } as SignalSplitViewEvents,
    defineCustomElement: defineSignalSplitView
});
