'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalTabsCustomEvent } from "@signal-web-ui/core";
import { SignalTabs as SignalTabsElement, defineCustomElement as defineSignalTabs } from "@signal-web-ui/core/dist/custom-elements/signal-tabs.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalTabsEvents = { onValueChange: EventName<SignalTabsCustomEvent<{ value: string }>> };

export const SignalTabs: StencilReactComponent<SignalTabsElement, SignalTabsEvents> = /*@__PURE__*/ createComponent<SignalTabsElement, SignalTabsEvents>({
    tagName: 'signal-tabs',
    elementClass: SignalTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as SignalTabsEvents,
    defineCustomElement: defineSignalTabs
});
